spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      generate-ddl: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
          order_inserts: true
          order_updates: true
          generate_statistics: false
          jdbc:
            batch_size: 500
            lob:
              non_contextual_creation: true
          show_sql: ${ENABLE_HIBERNATE_SQL:false}
          enable_lazy_load_no_trans: true
          format_sql: true
          event:
            merge:
              entity_copy_observer: allow
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration